### ISSUE TITLE
Snapshotter doesn't compile for ros2 humble

### ISSUE THREAD

**Issue by Kaju-Bubanja** [cellumation/snapshotter#15]
I am using ros2 humble since it is an LTE version, but snappshoter doesn't compile for it, I get following error:

```
ros2_humble/src/snapshotter/src/SingleMessageBuffer.cpp:90:21: error: no matching function for call to ‘rosbag2_cpp::Writer::write(const SerializedMsgPtr&, const string&, const string&, rclcpp::Time&)’
   90 |         writer.write(entry.msg, md.rosMetadata.name, md.rosMetadata.type, rewriteTimestamp);
```

was it developed for a specific version? And do you plan to make this package available for humble?

**Comment by arneboe** [comment]
I do not have access to a humble installation at the moment. I compiles fine on iron and jazzy.

According to the ros2bag github page, the method in question should exist in humble:
https://github.com/ros2/rosbag2/blob/humble/rosbag2_cpp/include/rosbag2_cpp/writer.hpp#L174

Did you install a specific version of rosbag2_cpp?

**Comment by Kaju-Bubanja** [comment]
I don't think so, but I anyways saw in the meantime, that ros2 bag record also has a built in snapshot mode, which is good enough for my needs, thank you for the help.
